### ISSUE TITLE
Dumper missing 

### ISSUE THREAD

**Issue by satyausc** [fmenabe/python-yamlordereddictloader#2]
It would be nice to have a Dumper Class implemented in this package. I was only able to load using loader, but it didn't serve the purpose of saving the yaml object dump back to the file

**Comment by fmenabe** [comment]
I add a Dumper class (in the [issue2](https://github.com/fmenabe/python-yamlordereddictloader/tree/issue2) branch).

The usage is similar to the Loader:

```python
import yaml, yamlordereddictloader
data = yaml.load(open('example.yml'), Loader=yamlordereddictloader.Loader)
yaml.dump(data, open('example.yml', 'w'), Dumper=yamlordereddictloader.Dumper, default_flow_style=False)
```

Is it working for you?
