### ISSUE TITLE
Use or support SafeLoader?

### ISSUE THREAD

**Issue by joernheissler** [fmenabe/python-yamlordereddictloader#6]
Hi,
thanks for creating this module!

I'd like to make use of yaml's safe_load function, as I don't trust the input completely.
Only way I found is to change the base class of your Loader to yaml.SafeLoader.
Is there a better way?
Cheers

**Comment by fmenabe** [comment]
I'd like to keep the unsafe loader, so I think it is better to add another class for safe loading a file (as for dumpers which have both ``Dumper`` and ``SafeDumper`` classes).

I created a *safeloader* branch in which I implemented a `SafeLoader` class inheriting from `yaml.SafeLoader`.

If it work for you, I'll merge the branch and release a new version.

**Comment by joernheissler** [comment]
Thanks, works!

**Comment by fmenabe** [comment]
I release a new version (0.4.0) with the SafeLoader.
