### ISSUE TITLE
Future of yamlordereddictloader?

### ISSUE THREAD

**Issue by mayou36** [fmenabe/python-yamlordereddictloader#8]
Hey, as we've successfully set up and are running our improved version of the library, [yamlloader](https://github.com/Phynix/yamlloader), I was wondering whether you may want to deprecate the `yamlordereddictloader` and instead point to `yamlloader`? (and maybe get active in the development there? You're of course welcome!)

Thanks again for the nice codebase!

**Comment by fmenabe** [comment]
Hey, nice work! 

I put a comment at the top of the README pointing to your project.
